### ISSUE TITLE
grpcServer.go:155: s.dispatcher nil when no config, causes Mixer panics.

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#1261]
As reported on istio-dev@:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x20f4430]

goroutine 70 [running]:
istio.io/mixer/pkg/api.(*grpcServer).Check(0xc420272b90, 0x31d96f0, 0xc420202300, 0xc4202fa400, 0xc420272b90, 0x24bf319, 0x5)
	pkg/api/grpcServer.go:155 +0x700
istio.io/api/mixer/v1._Mixer_Check_Handler.func1(0x31d96f0, 0xc420202300, 0x2391e60, 0xc4202fa400, 0xc4209dcfa0, 0xc42026c300, 0x0, 0xc42006c000)
	bazel-out/darwin_x86_64-fastbuild/genfiles/external/com_github_istio_api/mixer/v1/service.pb.go:98 +0x86
github.com/grpc-ecosystem/go-grpc-prometheus.UnaryServerInterceptor(0x31d96f0, 0xc420202300, 0x2391e60, 0xc4202fa400, 0xc42026c2e0, 0xc42026c300, 0x0, 0xc4200439b8, 0x1011d68, 0x50)
	external/com_github_grpc_ecosystem_go_grpc_prometheus/server.go:29 +0xd2
istio.io/api/mixer/v1._Mixer_Check_Handler(0x22be220, 0xc420272b90, 0x31d96f0, 0xc420202300, 0xc4209dcf00, 0x252d928, 0x0, 0x0, 0x0, 0x0)
	bazel-out/darwin_x86_64-fastbuild/genfiles/external/com_github_istio_api/mixer/v1/service.pb.go:100 +0x177
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420a02120, 0x2da49c0, 0xc4209fe9a0, 0xc420a7a000, 0xc4202630e0, 0x2dee760, 0xc420202420, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:753 +0xcd0
google.golang.org/grpc.(*Server).handleStream(0xc420a02120, 0x2da49c0, 0xc4209fe9a0, 0xc420a7a000, 0xc420202420)
	external/org_golang_google_grpc/server.go:955 +0x15a0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420358e00, 0xc420a02120, 0x2da49c0, 0xc4209fe9a0, 0xc420a7a000)
	external/org_golang_google_grpc/server.go:517 +0xa9
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:518 +0xa1
```

**Comment by mandarjog** [comment]
addressed by #1270
