### ISSUE TITLE
perftest doesn't run the all benchmarks

### ISSUE THREAD

**Issue by jmuk** [istio/mixer#1277]
A run of `./bin/perftest.sh` is like as follows:
```
% ./bin/perftest.sh
Perf test
BenchmarkExpressionAST/ok_1stAST-32             10000000               249 ns/op               2 B/op          2 allocs/op
BenchmarkExpressionAST/ok_2ndAST-32              3000000               561 ns/op              19 B/op          4 allocs/op
BenchmarkExpressionAST/ok_notfoundAST-32         2000000               605 ns/op              19 B/op          4 allocs/op
BenchmarkExpressionDirect/ok_1stDirect-32       100000000               16.7 ns/op             0 B/op          0 allocs/op
BenchmarkExpressionDirect/ok_2ndDirect-32       30000000                40.7 ns/op             0 B/op          0 allocs/op
BenchmarkExpressionDirect/ok_notfoundDirect-32          30000000                39.8 ns/op             0 B/op          0 allocs/op
PASS
ok      istio.io/mixer/pkg/expr 12.042s
PASS
ok      istio.io/mixer/pkg/attribute    0.136s
PASS
ok      istio.io/mixer/pkg/adapterManager       0.452s
```

This shows pkg/attribute and pkg/adapterManager don't have benchmarks anymore. On the other hand, `pkg/api/perf_test.go` and `pkg/il/interpreter/interpreterBenchmark_test.go` have benchmarks, but they don't run with `perftest.sh`.

Also; pkg/api/perf_test.go and pkg/il/interpreter/interperterBenchmark_test.go fail to run, like:
```
--- FAIL: BenchmarkIL
        interpreterBenchmark_test.go:121: Unable to parse program text: unrecognized opcode: 'ieq_i' @(L: 4, C: 3)
BenchmarkExpr/ExprBench/ok_1st-32               10000000               224 ns/op               2 B/op          2 allocs/op
BenchmarkExpr/ExprBench/ok_2nd-32                2000000               662 ns/op              19 B/op          4 allocs/op
BenchmarkExpr/ExprBench/not_found-32             2000000               578 ns/op              19 B/op          4 allocs/op
FAIL
exit status 1
FAIL    istio.io/mixer/pkg/il/interpreter       6.383s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14cc8e0]

goroutine 153 [running]:
istio.io/mixer/pkg/api.(*grpcServer).Check(0xc42040e0a0, 0x7f0d042b6ac0, 0xc4204949f0, 0xc4202a2200, 0xc42040e0a0, 0x42b1fe, 0x0)
        /usr/local/google/home/mukai/gopath/src/istio.io/mixer/pkg/api/grpcServer.go:156 +0x740
istio.io/mixer/vendor/istio.io/api/mixer/v1._Mixer_Check_Handler(0x1626fa0, 0xc42040e0a0, 0x7f0d042b6ac0, 0xc4204949f0, 0xc42040e5a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/google/home/mukai/gopath/src/istio.io/mixer/vendor/istio.io/api/mixer/v1/service.pb.go:91 +0x28d
istio.io/mixer/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420246000, 0x210e3e0, 0xc420402000, 0xc420246480, 0xc4202c2240, 0x216b0a0, 0xc420494ae0, 0x0, 0x0)
        /usr/local/google/home/mukai/gopath/src/istio.io/mixer/vendor/google.golang.org/grpc/server.go:753 +0xcd0
istio.io/mixer/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420246000, 0x210e3e0, 0xc420402000, 0xc420246480, 0xc420494ae0)
        /usr/local/google/home/mukai/gopath/src/istio.io/mixer/vendor/google.golang.org/grpc/server.go:955 +0x15a0
istio.io/mixer/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420296190, 0xc420246000, 0x210e3e0, 0xc420402000, 0xc420246480)
        /usr/local/google/home/mukai/gopath/src/istio.io/mixer/vendor/google.golang.org/grpc/server.go:517 +0xa9
created by istio.io/mixer/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /usr/local/google/home/mukai/gopath/src/istio.io/mixer/vendor/google.golang.org/grpc/server.go:518 +0xa1
exit status 2
FAIL    istio.io/mixer/pkg/api  0.468s
```

**Comment by jmuk** [comment]
this is fixed by https://github.com/istio/mixer/pull/1280
