### ISSUE TITLE
mixer client SIGSEGV in tracing.go:118

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#190]
```
mjog-macbookpro:mixer mjog$ bazel-bin/cmd/client/mixc check  -v 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xdf323]

goroutine 1 [running]:
panic(0x407b20, 0xc4200140a0)
	/private/var/tmp/_bazel_mjog/ae3ce3fe395e81daaa47c597b7ce79a2/bazel-sandbox/8f59cc23-cc6b-4786-8aab-6363079a8981-292/execroot/mixer/external/io_bazel_rules_go_toolchain/src/runtime/panic.go:500 +0x1a1
istio.io/mixer/pkg/tracing.(*Tracer).PropagateSpan(0xc4201557e8, 0x68d100, 0xc420014278, 0x68ffe0, 0x6cc2c8, 0xc42012b200, 0x1, 0x1)
	/private/var/tmp/_bazel_mjog/ae3ce3fe395e81daaa47c597b7ce79a2/bazel-sandbox/8f59cc23-cc6b-4786-8aab-6363079a8981-249/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/tracing/go_default_library.a.dir/istio.io/mixer/pkg/tracing/tracing.go:118 +0xb3
main.check(0xc4201ba090, 0xc420188ec0, 0x0, 0x2, 0x4be320)
	/private/var/tmp/_bazel_mjog/ae3ce3fe395e81daaa47c597b7ce79a2/bazel-sandbox/8f59cc23-cc6b-4786-8aab-6363079a8981-279/execroot/mixer/bazel-out/local-fastbuild/bin/cmd/client/mixc.a.dir/istio.io/mixer/cmd/client/check.go:54 +0x2c2
main.checkCmd.func1(0xc420194b40, 0xc420188ec0, 0x0, 0x2)
	/private/var/tmp/_bazel_mjog/ae3ce3fe395e81daaa47c597b7ce79a2/bazel-sandbox/8f59cc23-cc6b-4786-8aab-6363079a8981-279/execroot/mixer/bazel-out/local-fastbuild/bin/cmd/client/mixc.a.dir/istio.io/mixer/cmd/client/check.go:33 +0x51
github.com/spf13/cobra.(*Command).execute(0xc420194b40, 0xc420188d20, 0x2, 0x2, 0xc420194b40, 0xc420188d20)
	/private/var/tmp/_bazel_mjog/ae3ce3fe395e81daaa47c597b7ce79a2/bazel-sandbox/8f59cc23-cc6b-4786-8aab-6363079a8981-204/execroot/mixer/bazel-out/local-fastbuild/bin/external/com_github_spf13_cobra/go_default_library.a.dir/github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:636 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0xc420194900, 0xc42015fee8, 0xc42012b170, 0xc420194fc0)
	/private/var/tmp/_bazel_mjog/ae3ce3fe395e81daaa47c597b7ce79a2/bazel-sandbox/8f59cc23-cc6b-4786-8aab-6363079a8981-204/execroot/mixer/bazel-out/local-fastbuild/bin/external/com_github_spf13_cobra/go_default_library.a.dir/github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:722 +0x367
github.com/spf13/cobra.(*Command).Execute(0xc420194900, 0xc42015fee0, 0x1)
	/private/var/tmp/_bazel_mjog/ae3ce3fe395e81daaa47c597b7ce79a2/bazel-sandbox/8f59cc23-cc6b-4786-8aab-6363079a8981-204/execroot/mixer/bazel-out/local-fastbuild/bin/external/com_github_spf13_cobra/go_default_library.a.dir/github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:681 +0x2b
main.withArgs(0xc42000c250, 0x3, 0x3, 0x4be320)
	/private/var/tmp/_bazel_mjog/ae3ce3fe395e81daaa47c597b7ce79a2/bazel-sandbox/8f59cc23-cc6b-4786-8aab-6363079a8981-279/execroot/mixer/bazel-out/local-fastbuild/bin/cmd/client/mixc.a.dir/istio.io/mixer/cmd/client/main.go:103 +0x747
main.main()
	/private/var/tmp/_bazel_mjog/ae3ce3fe395e81daaa47c597b7ce79a2/bazel-sandbox/8f59cc23-cc6b-4786-8aab-6363079a8981-279/execroot/mixer/bazel-out/local-fastbuild/bin/cmd/client/mixc.a.dir/istio.io/mixer/cmd/client/main.go:114 +0x72
```

**Comment by douglas-reid** [comment]
Can this be closed now?
