### ISSUE TITLE
Regression [panic: runtime error:] - Fix adapterByName semantics: 

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#256]
pr #253   changed the way adapters lookup is handled.

At present, `validated.adapterByName` is keyed on `adapterName`
1. It should be keyed off `Impl` on config validation path
2. It should be keyed off `kind/name` on config runtime path

original problem
```
I0211 05:20:27.269363   61556 runtime.go:78] resolveRules (aspects:<kind:"quotas" params:&QuotasParams{QuotaDescriptorNames:[],} > aspects:<kind:"access-logs" params:&AccessLogsParams{LogName:access_log,Attributes:[],LogFormat:COMMON,CustomLogTemplate:,} > aspects:<kind:"application-logs" params:&ApplicationLogsParams{LogName:mixer_log,LogEntryDescriptorNames:[default],SeverityAttribute:,TimestampAttribute:,TimestampFormat:2006-01-02T15:04:05Z07:00,} > ) ==> /
I0211 05:20:27.269545   61556 runtime.go:108] Aspect rejected: access-logs not in set [map[denials:true lists:true quotas:true]]
I0211 05:20:27.269558   61556 runtime.go:108] Aspect rejected: application-logs not in set [map[denials:true lists:true quotas:true]]
I0211 05:20:27.269565   61556 handler.go:106] Resolved [1] ==> [0xc4201905f0]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb7ed3]

goroutine 11 [running]:
panic(0x5799e0, 0xc4200180a0)
	/Volumes/Untitled/BAZEL_OUT/execroot/mixer/external/io_bazel_rules_go_toolchain/src/runtime/panic.go:500 +0x1a1
istio.io/mixer/pkg/adapterManager.(*Manager).execute(0xc420015e00, 0x8c3540, 0xc420194f00, 0xc4201905f0, 0x8c74c0, 0xc4202e8300, 0x0, 0x0, 0x0)
	/Volumes/Untitled/BAZEL_OUT/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/adapterManager/go_default_library.a.dir/istio.io/mixer/pkg/adapterManager/manager.go:139 +0x123
istio.io/mixer/pkg/adapterManager.(*ParallelManager).worker(0xc4201c7fa0, 0xc4200750e0, 0xc420075140, 0xc4200e99c0)
	/Volumes/Untitled/BAZEL_OUT/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/adapterManager/go_default_library.a.dir/istio.io/mixer/pkg/adapterManager/parallelManager.go:116 +0x165
created by istio.io/mixer/pkg/adapterManager.NewParallelManager
	/Volumes/Untitled/BAZEL_OUT/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/adapterManager/go_default_library.a.dir/istio.io/mixer/pkg/adapterManager/parallelManager.go:53 +0x176
```

**Comment by douglas-reid** [comment]
Can we close this issue now?

**Comment by mandarjog** [comment]
Closing.
