### ISSUE TITLE
mixer dev minimal example not working

### ISSUE THREAD

**Issue by ldemailly** [istio/mixer#674]
Following the steps in https://github.com/istio/mixer/blob/master/doc/dev/development.md

near the end:
```
ldemailly-macbookpro:mixer ldemailly$ bazel-bin/cmd/server/mixs server \
>   --globalConfigFile testdata/globalconfig.yml \
>   --serviceConfigFile testdata/serviceconfig.yml  --logtostderr
*** serviceConfigFile and globalConfigFile are deprecated, use configStoreURL
proto: no coders for interface {}
proto: no encoder for Params interface {} [GetProperties]
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
istio.io/mixer/pkg/config/descriptor.Parse(0xc4204fd300, 0x1157, 0xc420011170, 0xc42001dc20)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-484/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/config/descriptor/go_default_library.a.dir/istio.io/mixer/pkg/config/descriptor/descriptor.go:160 +0xdad
istio.io/mixer/pkg/config.(*validator).validateDescriptors(0xc4208015e8, 0xc42001d541, 0x1a, 0xc4204fd300, 0x1157, 0xc42001dbc0)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-509/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/config/go_default_library.a.dir/istio.io/mixer/pkg/config/validator.go:240 +0x42
istio.io/mixer/pkg/config.(*validator).validate(0xc4208015e8, 0xc4202b3320, 0xc4202b3410, 0x0)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-509/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/config/go_default_library.a.dir/istio.io/mixer/pkg/config/validator.go:401 +0x274
istio.io/mixer/pkg/config.NewManager.func1(0xc4202b3320, 0xc420999900, 0x2329e0e, 0x1, 0xc4202b3320)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-509/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/config/go_default_library.a.dir/istio.io/mixer/pkg/config/manager.go:99 +0x2bc
istio.io/mixer/pkg/config.(*Manager).fetch(0xc4200be180, 0x2f23e10, 0x0, 0x10, 0xc42035de00, 0x0)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-509/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/config/go_default_library.a.dir/istio.io/mixer/pkg/config/manager.go:167 +0xfa
istio.io/mixer/pkg/config.(*Manager).fetchAndNotify(0xc4200be180)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-509/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/config/go_default_library.a.dir/istio.io/mixer/pkg/config/manager.go:180 +0x40
istio.io/mixer/pkg/config.(*Manager).Start(0xc4200be180)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-509/execroot/mixer/bazel-out/local-fastbuild/bin/pkg/config/go_default_library.a.dir/istio.io/mixer/pkg/config/manager.go:220 +0x2f
istio.io/mixer/cmd/server/cmd.runServer(0xc4200a4a80, 0x23a2ed0, 0x23a2ec8)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-584/execroot/mixer/bazel-out/local-fastbuild/bin/cmd/server/cmd/go_default_library.a.dir/istio.io/mixer/cmd/server/cmd/server.go:253 +0x11aa
istio.io/mixer/cmd/server/cmd.serverCmd.func2(0xc4201b9d40, 0xc42001adc0, 0x0, 0x5)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-584/execroot/mixer/bazel-out/local-fastbuild/bin/cmd/server/cmd/go_default_library.a.dir/istio.io/mixer/cmd/server/cmd/server.go:87 +0x3c
github.com/spf13/cobra.(*Command).execute(0xc4201b9d40, 0xc42001ad70, 0x5, 0x5, 0xc4201b9d40, 0xc42001ad70)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-274/execroot/mixer/bazel-out/local-fastbuild/bin/external/com_github_spf13_cobra/go_default_library.a.dir/github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:647 +0x231
github.com/spf13/cobra.(*Command).ExecuteC(0xc4201c7680, 0xc4201b0900, 0xc4201b9d40, 0xc4201c78c0)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-274/execroot/mixer/bazel-out/local-fastbuild/bin/external/com_github_spf13_cobra/go_default_library.a.dir/github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:734 +0x339
github.com/spf13/cobra.(*Command).Execute(0xc4201c7680, 0x6, 0x6)
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-274/execroot/mixer/bazel-out/local-fastbuild/bin/external/com_github_spf13_cobra/go_default_library.a.dir/github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:692 +0x2b
main.main()
	/private/var/tmp/_bazel_ldemailly/4ba81f375d2899b7f5517b55ee04718a/bazel-sandbox/c0e694bc-f120-41be-91c8-70a99aadaf35-587/execroot/mixer/bazel-out/local-fastbuild/bin/cmd/server/mixs.a.dir/istio.io/mixer/cmd/server/main.go:27 +0x8f
```

**Comment by douglas-reid** [comment]
@mandarjog anything preventing us from removing the legacy option altogether at this point?

**Comment by ldemailly** [comment]
better version from douglas on slack:
```
./bazel-bin/cmd/server/mixs server --configStoreURL=fs://$(pwd)/testdata/configRoot --alsologtostderr -v=5
```
I'm updating the doc

**Comment by ldemailly** [comment]
when running the mixc check:
```
ldemailly-macbookpro:mixer ldemailly$ ./bazel-bin/cmd/client/mixc check 
I0508 16:19:31.249354   50538 <autogenerated>:5] kubernetes:getting kubeconfig from: ""
W0508 16:19:31.249437   50538 client_config.go:495] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0508 16:19:31.249823   50538 client_config.go:500] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
proto: no coders for interface {}
proto: no encoder for Params interface {} [GetProperties]
proto: no coders for interface {}
proto: no encoder for Params interface {} [GetProperties]
Check RPC returned INTERNAL (builder: name:"default" kind:"attributes" impl:"kubernetes" params:&Params{KubeconfigPath:,CacheRefreshDuration:5m0s,SourceUidInputName:sourceUID,TargetUidInputName:targetUID,OriginUidInputName:originUID,PodLabelForService:app,SourcePrefix:source,TargetPrefix:target,OriginPrefix:origin,LabelsValueName:Labels,PodNameValueName:PodName,PodIpValueName:PodIP,HostIpValueName:HostIP,NamespaceValueName:Namespace,ServiceAccountValueName:ServiceAccountName,ServiceValueName:Service,TargetServiceInputName:targetService,ClusterDomainName:svc.cluster.local,}  aspect: kind:"attributes" adapter:"default" params:&AttributesGeneratorParams{InputExpressions:map[string]string{originUID: origin.uid | "",sourceUID: source.uid | "",targetService: request.headers["authority"] | request.host | "",targetUID: target.uid | "",},AttributeBindings:map[string]string{source.ip: sourcePodIp,source.labels: sourceLabels,source.name: sourcePodName,source.namespace: sourceNamespace,source.service: sourceService,source.serviceAccount: sourceServiceAccountName,target.ip: targetPodIp,target.labels: targetLabels,target.name: targetPodName,target.namespace: targetNamespace,target.service: targetService,target.serviceAccount: targetServiceAccountName,},} :could not retrieve kubeconfig: invalid configuration: no configuration has been provided)
```

**Comment by douglas-reid** [comment]
there is already an issue for the kubernetes adapter documentation: https://github.com/istio/mixer/issues/571

**Comment by ldemailly** [comment]
fix:
```
ldemailly-macbookpro:mixer ldemailly$ ./bazel-bin/cmd/client/mixc check  -a target.service=f.default.svc.cluster.local
Check RPC returned OK
```
